{{- if .Values.supabase.vector.useDaemonSet -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-supabase-vector-ds
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: supabase-vector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: vector
    vector.dev/exclude: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase-vector
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: vector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase-vector
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: vector
    spec:
      serviceAccountName: {{ .Release.Name }}-supabase-vector
      containers:
        - name: vector
          image: "timberio/vector:{{ .Values.supabase.vector.image.tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - --config
            - /etc/vector/vector.yml
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LOGFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-analytics
                  key: apiKey
          {{- with .Values.supabase.vector.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 9001
              protocol: TCP
              name: api
          volumeMounts:
            {{- with .Values.supabase.vector.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - mountPath: /etc/vector/vector.yml
              name: vector-config
              subPath: vector.yml
            - mountPath: /etc/vector/secret.sh
              name: vector-config
              subPath: secret.sh
          {{- with .Values.supabase.vector.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- with .Values.supabase.vector.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: vector-config
          configMap:
            name: {{ .Release.Name }}-supabase-vector-config
            defaultMode: 0777
      {{- with .Values.supabase.vector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
